// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $lobby_index from "./routes/lobby/index.tsx";
import * as $lobby_socket from "./routes/lobby/socket.ts";
import * as $observe_gameId_index from "./routes/observe/[gameId]/index.tsx";
import * as $observe_gameId_socket from "./routes/observe/[gameId]/socket.ts";
import * as $play_gameId_sessionId_index from "./routes/play/[gameId]/[sessionId]/index.tsx";
import * as $play_gameId_sessionId_socket from "./routes/play/[gameId]/[sessionId]/socket.ts";
import * as $Lobby from "./islands/Lobby.tsx";
import * as $ObserveIsland from "./islands/ObserveIsland.tsx";
import * as $PlayIsland from "./islands/PlayIsland.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/lobby/index.tsx": $lobby_index,
    "./routes/lobby/socket.ts": $lobby_socket,
    "./routes/observe/[gameId]/index.tsx": $observe_gameId_index,
    "./routes/observe/[gameId]/socket.ts": $observe_gameId_socket,
    "./routes/play/[gameId]/[sessionId]/index.tsx":
      $play_gameId_sessionId_index,
    "./routes/play/[gameId]/[sessionId]/socket.ts":
      $play_gameId_sessionId_socket,
  },
  islands: {
    "./islands/Lobby.tsx": $Lobby,
    "./islands/ObserveIsland.tsx": $ObserveIsland,
    "./islands/PlayIsland.tsx": $PlayIsland,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
